const CREATE_USER = 'chat/CREATE_USER';
const CREATE_ROOM = 'chat/CREATE_ROOM';
const LEAVE_ROOM = 'chat/LEAVE_ROOM';
const SEND_MESSAGE = 'chat/SEND_MESSAGE';
const SAVE_PREV_URL = 'chat/SAVE_PREV_URL';
const SAVE_MESSAGE = 'chat/SAVE_MESSAGE';

export{
    CREATE_USER,
    CREATE_ROOM,
    LEAVE_ROOM,
    SEND_MESSAGE,
    SAVE_PREV_URL,
    SAVE_MESSAGE
}